const movies = [
    {
        _id: "C8uPFeLMiDsPhHMHBAic",
        title: "jnLaYYy7mO",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 10,
        dailyRentalRate: 4.8,
    },
    {
        _id: "mozmbcj6b8u3WdpRZCyt",
        title: "IWw8niyfDF",
        genre: {_id: "0LnZmGKwyOT8Ecc2s5Y1", name: "Crime"},
        numberInStock: 8,
        dailyRentalRate: 3.1,
    },
    {
        _id: "YwdFU9kt6e0P8Bwgj4iP",
        title: "ehQE2KWp43",
        genre: {_id: "ztSseL1th5zK2LcGraTf", name: "Adventure"},
        numberInStock: 2,
        dailyRentalRate: 1.4,
    },
    {
        _id: "X7qbc8AEZpevVkb1GgLl",
        title: "OXXROBathp",
        genre: {_id: "jwCZqomgdc5UzOtL6pYK", name: "Fantasy"},
        numberInStock: 5,
        dailyRentalRate: 3.8,
    },
    {
        _id: "MbEQKVfpDfDjVzHbv4sk",
        title: "pYbZ0sF7eD",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 1,
        dailyRentalRate: 2.0,
    },
    {
        _id: "XGezJsNDaWGR9AfKOjnH",
        title: "POWuO75gMP",
        genre: {_id: "tAoLdsDBO2j7khtxybD9", name: "Historical"},
        numberInStock: 6,
        dailyRentalRate: 0.4,
    },
    {
        _id: "Cys2sYDUCHO25hLHUdVB",
        title: "a47wrZx9VP",
        genre: {_id: "ztSseL1th5zK2LcGraTf", name: "Adventure"},
        numberInStock: 10,
        dailyRentalRate: 4.8,
    },
    {
        _id: "FWP4eI2OEUy8V3WcvXnO",
        title: "Il01MNmrPq",
        genre: {_id: "jwCZqomgdc5UzOtL6pYK", name: "Fantasy"},
        numberInStock: 2,
        dailyRentalRate: 3.3,
    },
    {
        _id: "o3tBZYR6Fi2jMABJvtMz",
        title: "6R63RtomlK",
        genre: {_id: "0LnZmGKwyOT8Ecc2s5Y1", name: "Crime"},
        numberInStock: 7,
        dailyRentalRate: 4.9,
    },
    {
        _id: "llg23ID0tW2k99ybXi8P",
        title: "Q9Pu8cdkOd",
        genre: {_id: "tAoLdsDBO2j7khtxybD9", name: "Historical"},
        numberInStock: 5,
        dailyRentalRate: 1.8,
    },
    {
        _id: "mZwHbqan2Gq0V1UnDiMm",
        title: "wwwNc9jKk2",
        genre: {_id: "tAoLdsDBO2j7khtxybD9", name: "Historical"},
        numberInStock: 9,
        dailyRentalRate: 3.3,
    },
    {
        _id: "IpcbSFfymsqhcP5appOk",
        title: "ePvTwscsjl",
        genre: {_id: "tAoLdsDBO2j7khtxybD9", name: "Historical"},
        numberInStock: 3,
        dailyRentalRate: 1.2,
    },
    {
        _id: "btztnl7ZXSDgN739D5zi",
        title: "gyyq6TcpvX",
        genre: {_id: "ztSseL1th5zK2LcGraTf", name: "Adventure"},
        numberInStock: 6,
        dailyRentalRate: 2.2,
    },
    {
        _id: "MUpQTd5GKoFoyaom9rB0",
        title: "xduJCI35zf",
        genre: {_id: "VPmJTCNuJkM8eTgDiVnj", name: "Drama"},
        numberInStock: 10,
        dailyRentalRate: 3.4,
    },
    {
        _id: "OIIi1CNzyV3ZBvhm7I08",
        title: "Rh8vHlJGK4",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 6,
        dailyRentalRate: 5.0,
    },
    {
        _id: "e1c00sZ0LaLwC2NwJysP",
        title: "PB2YARaQF7",
        genre: {_id: "jwCZqomgdc5UzOtL6pYK", name: "Fantasy"},
        numberInStock: 10,
        dailyRentalRate: 1.7,
    },
    {
        _id: "FuaKfEXNP3ejetPmj0Pb",
        title: "IbhevhEFpp",
        genre: {_id: "ztSseL1th5zK2LcGraTf", name: "Adventure"},
        numberInStock: 7,
        dailyRentalRate: 5.4,
    },
    {
        _id: "rkSBq8sTscgTp4qMYowP",
        title: "5cFKSApter",
        genre: {_id: "jwCZqomgdc5UzOtL6pYK", name: "Fantasy"},
        numberInStock: 3,
        dailyRentalRate: 1.6,
    },
    {
        _id: "CTfZ3Tm11fsPGIHm7t9l",
        title: "iTYqZs9Uzk",
        genre: {_id: "tAoLdsDBO2j7khtxybD9", name: "Historical"},
        numberInStock: 6,
        dailyRentalRate: 3.2,
    },
    {
        _id: "vuns0DJ7wx0PzY8Sd5py",
        title: "EyhqIA2TYx",
        genre: {_id: "ztSseL1th5zK2LcGraTf", name: "Adventure"},
        numberInStock: 2,
        dailyRentalRate: 3.9,
    },
    {
        _id: "EKY9ZCz4E0lU5ujqcSEB",
        title: "cR58Wxaujn",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 1,
        dailyRentalRate: 0.0,
    },
    {
        _id: "0rt5orLZzMuPn9AxRoxI",
        title: "Y24rUqOw4l",
        genre: {_id: "VPmJTCNuJkM8eTgDiVnj", name: "Drama"},
        numberInStock: 9,
        dailyRentalRate: 4.8,
    },
    {
        _id: "z4PFg9thMVzIe1KOA1TX",
        title: "aZnebtTgNT",
        genre: {_id: "ztSseL1th5zK2LcGraTf", name: "Adventure"},
        numberInStock: 7,
        dailyRentalRate: 1.4,
    },
    {
        _id: "yhGAygBxXhCrKLZLFoeJ",
        title: "ftLhdO3k3S",
        genre: {_id: "ztSseL1th5zK2LcGraTf", name: "Adventure"},
        numberInStock: 3,
        dailyRentalRate: 2.3,
    },
    {
        _id: "x1x6TjdL4sVszXeJBee1",
        title: "VEzt0lrwpe",
        genre: {_id: "ztSseL1th5zK2LcGraTf", name: "Adventure"},
        numberInStock: 4,
        dailyRentalRate: 2.5,
    },
    {
        _id: "6yb73s5Oj50rwSuET2Sh",
        title: "rbDelWOSgD",
        genre: {_id: "h9GmVVsziSptDacwP9rh", name: "Action"},
        numberInStock: 5,
        dailyRentalRate: 2.7,
    },
    {
        _id: "aqsTxyZm57INTVjby7FG",
        title: "h4hPVp9QlT",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 4,
        dailyRentalRate: 0.3,
    },
    {
        _id: "1KGnSGeEwVpoCcmFCF1V",
        title: "dYdyj8oNho",
        genre: {_id: "VPmJTCNuJkM8eTgDiVnj", name: "Drama"},
        numberInStock: 7,
        dailyRentalRate: 0.6,
    },
    {
        _id: "2CDf0MmABNMIVYTHEQhR",
        title: "Rm8mWxDexa",
        genre: {_id: "VPmJTCNuJkM8eTgDiVnj", name: "Drama"},
        numberInStock: 7,
        dailyRentalRate: 3.9,
    },
    {
        _id: "iLLdScxOrQzNEt57MMRI",
        title: "JEtWewvdfW",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 9,
        dailyRentalRate: 0.6,
    },
    {
        _id: "uK2bwNndz3T8n74lt9Bo",
        title: "cCqP0c8dfs",
        genre: {_id: "0LnZmGKwyOT8Ecc2s5Y1", name: "Crime"},
        numberInStock: 5,
        dailyRentalRate: 3.7,
    },
    {
        _id: "J1tffHbbsaZXomKIMyqm",
        title: "vCaeBSboMp",
        genre: {_id: "dvkywEdzY06NYeVLLwFo", name: "Horror"},
        numberInStock: 6,
        dailyRentalRate: 1.4,
    },
    {
        _id: "CwAj7C875qMDOc6OsHRx",
        title: "Qyz1cyll8U",
        genre: {_id: "dvkywEdzY06NYeVLLwFo", name: "Horror"},
        numberInStock: 7,
        dailyRentalRate: 0.6,
    },
    {
        _id: "WYuKJzlEenRgyNYjYElZ",
        title: "QtrBlpoPs9",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 6,
        dailyRentalRate: 3.2,
    },
    {
        _id: "KPgNjPzSiLqubc2WOcWD",
        title: "1VZ2sTgYYv",
        genre: {_id: "tAoLdsDBO2j7khtxybD9", name: "Historical"},
        numberInStock: 10,
        dailyRentalRate: 1.5,
    },
    {
        _id: "Nl18YoMkdaMa3JBmlcw9",
        title: "mDWYCHNBFR",
        genre: {_id: "ztSseL1th5zK2LcGraTf", name: "Adventure"},
        numberInStock: 6,
        dailyRentalRate: 5.0,
    },
    {
        _id: "3jLNRumpcLgL8NitD9Lb",
        title: "8ijZAwxurF",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 1,
        dailyRentalRate: 3.9,
    },
    {
        _id: "RxygZWbYdA6p6KPx9wOj",
        title: "8aRmOwzhAt",
        genre: {_id: "VPmJTCNuJkM8eTgDiVnj", name: "Drama"},
        numberInStock: 9,
        dailyRentalRate: 4.5,
    },
    {
        _id: "0AESDwa8Oetu2c1YkA5i",
        title: "jRm9nQ0BYt",
        genre: {_id: "0LnZmGKwyOT8Ecc2s5Y1", name: "Crime"},
        numberInStock: 9,
        dailyRentalRate: 1.3,
    },
    {
        _id: "reJwQ6KYTRF7xfw1eLDv",
        title: "jz7N4erekU",
        genre: {_id: "0LnZmGKwyOT8Ecc2s5Y1", name: "Crime"},
        numberInStock: 2,
        dailyRentalRate: 3.5,
    },
    {
        _id: "35MFcQVKonGMcwpWLAwi",
        title: "FEu11JVCVX",
        genre: {_id: "dvkywEdzY06NYeVLLwFo", name: "Horror"},
        numberInStock: 9,
        dailyRentalRate: 3.7,
    },
    {
        _id: "IXtPNgK9guYnVNcOiBfT",
        title: "Q4AIUFCKFv",
        genre: {_id: "VPmJTCNuJkM8eTgDiVnj", name: "Drama"},
        numberInStock: 10,
        dailyRentalRate: 5.0,
    },
    {
        _id: "AhTj4IEcKOcP4YioxSoW",
        title: "emVYMEXLd9",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 6,
        dailyRentalRate: 4.8,
    },
    {
        _id: "SWegkhnWMmROZVrwi3Ob",
        title: "ynnxAHZjZQ",
        genre: {_id: "0LnZmGKwyOT8Ecc2s5Y1", name: "Crime"},
        numberInStock: 4,
        dailyRentalRate: 5.3,
    },
    {
        _id: "xLcZCnmmwK2hIR2JxDPM",
        title: "drTR8TG6ss",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 4,
        dailyRentalRate: 4.5,
    },
    {
        _id: "Kecbmc3rihojqlDay99t",
        title: "WyuggTUMRc",
        genre: {_id: "jwCZqomgdc5UzOtL6pYK", name: "Fantasy"},
        numberInStock: 9,
        dailyRentalRate: 4.4,
    },
    {
        _id: "aVUbDDWjEshaYKi6zO0S",
        title: "Drakeciq8r",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 6,
        dailyRentalRate: 0.3,
    },
    {
        _id: "agUWy6NWaOJdRzFuoC7g",
        title: "fIu55dkyZQ",
        genre: {_id: "tAoLdsDBO2j7khtxybD9", name: "Historical"},
        numberInStock: 10,
        dailyRentalRate: 1.0,
    },
    {
        _id: "YtY5UyzTVwBntrO4IJ7V",
        title: "UrbiFZXPgN",
        genre: {_id: "jwCZqomgdc5UzOtL6pYK", name: "Fantasy"},
        numberInStock: 10,
        dailyRentalRate: 5.6,
    },
    {
        _id: "5JnRgj3Ma0cpVn3CeFTq",
        title: "XrD445NHAm",
        genre: {_id: "WTLloGDEqVAA5snrP0Kj", name: "Comedy"},
        numberInStock: 10,
        dailyRentalRate: 3.9,
    },
]

export function getMovies() {
    return movies
}

export function getMovieById(id) {
    return movies.filter(movie => movie._id === id)[0]
}
